import crypto from 'crypto';

export default class HmacGenerator {
  constructor(secretKey) {
    this.secretKey = secretKey;
  }
  
  generateHmac(value) {
    return crypto.createHmac('sha3-256', this.secretKey)
                .update(value.toString())
                .digest('hex')
                .toUpperCase();
  }
}


// To recheck the results take secret key + number computer chose go to https://cryptotools.net/hmac (choose sha3-256) and check resulting HMAC === HMAC generated by the program